#!/bin/sh
#
# incremental backups using tar and rsync
# works transparently over SSH by mounting with sshfs
# unencrypted files are never exposed on the remote system
# root privileges are required to preserve permissions (see tar man page for -p)
#
# TODO: cleanup
#
#set -x

passprompt() {
    stty -echo
    printf "Backup password: "
    read pass
    stty echo
    echo
}

cleanup() {
    rm "$repo/.lock"
    # test -e "$fetchdir/$(dst).tar" && rm -r "$fetchdir/$(dst).tar"
}

parse() { # parse backup file name and their metadata eg:
    # home~yaneko~devel~tarka~test-in~2025-10-16__16-22.39=fb63256f!0.tar.gpg
    set -- "$(basename "$1")"
    psrc="$(echo "~${1%~*}~" | tr '~' '/')"
    pmeta="${1##*~}"

    pdate="${pmeta%=*}"
    phash="${pmeta##*=}"
    phash="${phash%!*}"
    pnr="${pmeta#*!}"
    pnr="${pnr%--*}"
    pnr="${pnr%%.*}"
    ptag="${pmeta#*!}"
    ptag="${ptag#*--}"
    ptag="${ptag%%.*}"
    test "$ptag" = "$pnr" && ptag=""

    # echo "psrc $psrc"
    # echo "date $pdate"
    # echo "hash $phash"
    # echo "pnr $pnr"
    # echo "pnr $ptag"
}

mangle() {  # mangle directory to use as backup filename
    mangle="${1%/}"
    mangle="$(echo "${mangle#/}" | tr '/' '~')"
    printf "%s" "$mangle"
}

realmangle() {
    mangle "$(realpath "$1")"
}

latest() { # latest backup for directory
    latest=""
    for i in "$repo"/"$(realmangle $1)"*; do
        if test "${i##*.}" != snar; then
            latest="$i"
        fi
    done
    printf "%s" "$latest"
}


merge_dir() { # path hash | directory for merging tars aka extract dir
    printf "%s" "${fetchdir}/$(realmangle "$1")~$2"
}

dst() { # destination name for new backup
    printf "%s" "$(realmangle $src)~${date}=${hash}!${nr}${tag:+--}${tag}"
}

exits() {
    printf "%s; exiting\n" "--! $1" >&2
    exit 1
}

encrypt() {
    gpg -q --batch --passphrase "$pass" --symmetric --cipher-algo AES256 "$@" || exits "gpg encrypt error"
}

fetch() { # fetches from sshfs
    [ "$repo" = "$fetchdir" ] && return
    echo "-- fetch"
    for i in "$repo"/"$(realmangle $1)"*"$2"*.gpg; do
        parse "$i"
        test "$pnr" -gt "${3-2137}" && break
        echo "$i"
        sync "$i" "$fetchdir/${i#$repo}" || exits "failed fetching $i"
    done
}

ungpg() {
    echo "-- ungpg"
    for i in "$fetchdir"/"$(realmangle $1)"*"$2"*.gpg; do
        parse "$i"
        test "$pnr" -gt "${3-2137}" && break
        echo "$i..."
        gpg -q --batch --passphrase "$pass" --output "${i%.gpg}" --decrypt "$i" || exits "gpg decrypt error"
    done
}

untar() {
    echo "-- untar"
    for i in "$fetchdir"/"$(realmangle $1)"*"$2"*.tar; do
        parse "$i"
        test "$pnr" -gt "${3-2137}" && break
        echo "$i..."
        tar -xpf "$i" -C "$fetchdir/" -G || exits "error untaring archive "$i""
        rm "$i"
    done
    test -e "$(merge_dir "$1" "$2")" || exits "assertion failed; merge directory is absent"
}

genhash() { # each set of incremental backups is grouped by hash
    hash=$(date +%s | md5sum | head -c 8)
    hash="bcab3cb1"
    while "$repo/$(realmangle $src)"*"$hash"*.gpg; do
        hash=$(date +%s | md5sum | head -c 8)
    done
    printf "%s" "$hash"
}

list() {
    printf "%-40s %-30s %-8s %-4s %s\n" "src" "date" "hash" "nr" "tag"
    for i in "$repo/${1+$(realmangle $1)}"*.gpg; do
        test -e "$i" || break
        parse "$i"
        printf "%-40s %-30s %8s %-4s %s\n" "$psrc" "$pdate" "$phash" "$pnr" "$ptag"
    done
}

sync() {
    rsync "${3--q}" -az --delete  "${1}" "${2}" #--exclude-from="$0-ignore"
}

targ() { # tar with -g
    snar="$repo/${1#$fetchdir/}.snar"
    test "$isfull" -eq 0 && ! test -e "$snar" && exits "snar at $snar doesn't exist"
    echo "-- tar with $snar..."
    tar -cpf "${2}.tar" "${1}" -g  "$snar" -P --lzma --xform="s|^${fetchdir}/||" || exits "archiving $1 failed"
}

usage() {
    cat >&2 <<EOF
$0 cmd repo args
cmd:
    full
    incremental
    list
    restore
EOF
    exit 1
}

is_repo() {
    if ! test -e "$repo/.repo"; then
        echo "-- not backup repository; exiting" >&2
        usage
    fi
}

info_header() {
    printf "%-15s : %s\n" "temp" "$fetchdir"
    printf "%-15s : %s\n" "tag" "$tag"
    printf "%-15s : %s\n" "repo" "$repo"
    printf "%-15s : %s\n" "extract" "$xdir"
    printf "%-15s : %s\n" "latest" "$latest"
    printf "%-15s : %s\n" "destination" "$(dst)"
    echo "----------"
}

restore() { # src hash
    test -n "$1" || usage
    test -n "$2" || usage

    passprompt
    src="$(realpath "$1")"
    hash="$2"
    nr="$3"

    if test -e "$src"; then
        read -p "$src will be overwritten; continue? (yes/n): " choice
        test "$choice" != "yes" && exit 0
    fi
    info_header # debug info
    fetch "$src" "$hash" "$nr"
    ungpg "$src" "$hash" "$nr"
    untar "$src" "$hash" "$nr"
    echo "-- restore $src"
    sync "$(merge_dir "$src" "$hash")/" "$src" -v
    rm -r "$(merge_dir "$src" "$hash")"
}

backup() {
    test -n "$1" || usage

    passprompt
    src="$(realpath $1)"
    tag=${2:-}
    # %S is needed for correct ordering just in case of multiple backups in the same minut
    date=$(date +'%Y-%m-%d__%H-%M.%S')
    latest=$(latest "$src")

    if test "$isfull" -eq 1 || test ! -e "$latest"; then
        isfull=1
        hash="$(genhash)"
        nr="0"
    else
        parse "$latest"
        hash="$phash"
        nr="$((pnr+1))"
    fi

    mkdir -p "$fetchdir"
    xdir=$(merge_dir "$src" "$hash") # target for sync and the tar source
    info_header # debug info
    exit 0
    if test "$isfull" -eq 0; then
        fetch "$src" "$hash"
        ungpg "$src" "$hash"
        untar "$src" "$hash"
    fi
    echo "-- sync fetch dir"
    sync "$src/" "$xdir"
    targ "$xdir" "$fetchdir/$(dst)"
    encrypt "$fetchdir/$(dst)".tar
    echo "-- sync $repo/$repo.tar.gpg"
    rsync -v "$fetchdir/$(dst)".tar.gpg "$repo/$(dst).tar.gpg"
    touch "$repo/.repo"
    rm -r "$xdir"
    rm "$fetchdir/$(dst).tar"
}

disconn() {
    arg=$?
    fusermount -u "$repo"
    rmdir "$repo"
    cleanup
    exit $arg
}

main() {
    test -n "$1" || usage
    test -n "$2" || usage

    isfull=0
    cmd="$1"
    case "$2" in
        *:*)
            fetchdir=$(mktemp -d)
            repo=$(mktemp -d)
            sshfs "$2" "$repo" || exits "error connecting with server; check auth"
            trap disconn EXIT
            ;;
        *)
            repo="$(realpath ${2%/})"
            fetchdir="${repo}"
            trap cleanup EXIT
            ;;
    esac
    shift 2
    test -e "$repo/.lock" && exits "backup repository is locked; either wait for job to finish or delete .lock"
    touch "$repo/.lock"
    case "$cmd" in
        f*) isfull=1; backup  "$@"; exit;;
        i*) is_repo;  backup  "$@"; exit;;
        r*) is_repo;  restore "$@"; exit;;
        l*) is_repo;  list    "$@"; exit;;
        *) exits "invalid operation: $cmd";;
    esac
}

main "$@"
